spring:
  application:
    name: todo-list
  datasource:
    url: jdbc:postgresql://localhost:5432/todoDB
    username: postgres
    password: 123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        "[format_sql]": true
        "[use_sql_comments]": true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/Todo-Project

logging:
  level:
    "[org.hibernate.orm.jdbc.bind]": trace